### ISSUE TITLE
Hide expert panels in normal mode on MEM options panel

### ISSUE THREAD

**Issue by ilianAZZ** [multifunkim/best-brainstorm#17]
**Is your feature request related to a problem? Please describe.**
Displaying "expert" options in normal mode might be intimidating. Even though these options are disabled, their presence can be unnecessary and potentially confusing.

**Describe the solution you'd like**
 It would be better to hide them and only show them when expert mode is activated.

**Comment by Edouard2laire** [comment]
Closing as it is solved in #13
