### ISSUE TITLE
Editing option panel  for MEM

### ISSUE THREAD

**Issue by Edouard2laire** [multifunkim/best-brainstorm#5]
Hello 

**Describe the bug**
When using the process,  Sources > Compute sources: BEst, we can open the panel to enter the MEM option using the Edit button. After entering all the parameters, and closing it by clicking "ok". If we try to reopen the panel using again the Edit button, an error appears. 

**To Reproduce**
1. Go to Sources > Compute sources: BEst
2. Click on Edit and enter some parameters
3. Click on Ok. 
4. Click again on Edit and see the error

**Screenshot**

(1)
<img width="484" alt="Capture d’écran 2023-06-07 à 10 06 04" src="https://github.com/multifunkim/best-brainstorm/assets/24530402/327327de-7574-424f-af45-32e87fc399a4">

(2)
<img width="728" alt="Capture d’écran 2023-06-07 à 10 13 30" src="https://github.com/multifunkim/best-brainstorm/assets/24530402/abde69c3-3fd6-4c8c-aba2-8717d184d739">

(4)
<img width="829" alt="Capture d’écran 2023-06-07 à 10 05 54" src="https://github.com/multifunkim/best-brainstorm/assets/24530402/1263f28c-a42f-4fab-b7d7-8e33a894bcf7">

**Expected behavior**
When clicking again on Edit, the previously entered parameter should appear in the edit panel. 

**Additional context**
The error also appears for NIRS

@ftadel, I am tagging you in case you have any idea on how to solve this bug :)

**Comment by Edouard2laire** [comment]
hi  @rcassani 


I started to work again on that issue and reorganized the panel so its easier to debug and it is almost fully functional: 
https://github.com/Edouard2laire/best-brainstorm/blob/new_panel/gui/panel_brainentropy.m

However, I have some issues with the display and how vfill / hfill works

First, the reference panel gets all squished although I specified a minimum size then when I hide some components, the other components don't move to fill the blank but leave a gap in the window which looks quite weird: 


![image](https://github.com/multifunkim/best-brainstorm/assets/24530402/12d51741-6401-476b-8e86-66cdc9ed181f)

![image](https://github.com/multifunkim/best-brainstorm/assets/24530402/5f754254-9c32-4f3d-b234-812c244e308a)
![image](https://github.com/multifunkim/best-brainstorm/assets/24530402/f4d0fa8c-26bd-402b-a8be-5cc4d0217220)
![image](https://github.com/multifunkim/best-brainstorm/assets/24530402/569635c1-2634-44ee-b11d-ad81d27f2a78)


Do you think you could have time to help me on that? 

Thanks a lot, 
Edouard

**Comment by rcassani** [comment]
Hi @Edouard2laire, a panel that behaves more or less as you wish is [`panel_inverse_2018`](https://github.com/rcassani/brainstorm3/blob/master/toolbox/inverse/panel_inverse_2018.m)

> Do you think you could have time to help me on that?

Could you generate mock-ups for the three options?
Also, which branch is the one to test those changes?

**Comment by Edouard2laire** [comment]
Hi. 

The branch is new_panel  from my fork: https://github.com/Edouard2laire/best-brainstorm/tree/new_panel 

here is an illustration showing left what the code is producing vs what I am trying to achieve: 

<img width="834" alt="image" src="https://github.com/multifunkim/best-brainstorm/assets/24530402/86529514-1b23-4236-a53c-5d939921aee0">

Basically on the left, all the blank spaces correspond to options that are only shown during wMEM or rMEM. 

I looked at the example and at the panel we did for nirstorm; but I am still not sure about why the hidden panel still take room in the main panel, creating those blank spaces.

**Comment by Edouard2laire** [comment]
hi @rcassani ,

I know you are very busy, but I was wondering if you had a bit of time to look into that issue?  We will soon be able to merge https://github.com/multifunkim/best-brainstorm/pull/13 in Best, so I would like to fix those panel issue at the same time so we can announce the new panel at the same time of the release :) 


Let me know if you would like us to meet to check that together.
Edouard

**Comment by Edouard2laire** [comment]
Closing as it is solved in https://github.com/multifunkim/best-brainstorm/pull/13
